### ISSUE TITLE
[1.2] crafting recipes missing for all compasses

### ISSUE THREAD

**Issue by kreezxil** [Mrbysco/StructureCompass#1]
## Client Info
* Minecraft Version:
1.14.4
* Forge Version: 28.1.90
* Mod Version: 1.2
* Java Version: 1.8_231

## Issue Description
crafting recipes for the compass are missing

## Reproduce Steps
look in JEI

## Additional Information
I'll be using a resource loader to add recipes for them until you get this fixed.

**Comment by kreezxil** [comment]
Opening your mod shows the recipes to be missing.

![image](https://user-images.githubusercontent.com/3880072/68863579-43872900-06b5-11ea-9b9f-d5f043027f20.png)

**Comment by Mrbysco** [comment]
The compasses were supposed to be given recipes by the pack creators.

**Comment by Mrbysco** [comment]
In the 1.16.5 version the compass now has a recipe
