### ISSUE TITLE
[Suggestion]: (1.20.1) Compass missing from tag

### ISSUE THREAD

**Issue by ModernGamingWorld** [Mrbysco/StructureCompass#14]
### General Info

- [ ] I would like to propose new content
- [X] I would like to propose changes
- [ ] I would like to propose another thing

### Suggestion Description

Currently your compass is missing from the #minecraft:compasses tag and would like it to be added

**Comment by Mrbysco** [comment]
Is there any use-case for it being in that tag?

**Comment by ModernGamingWorld** [comment]
Well kinda, I have a custom mod for my modpack that use that tag for some custom recipes and it would make mine and anyone else's life much easier than having to go in an add it by ourselves

**Comment by Mrbysco** [comment]
Done in https://github.com/Mrbysco/StructureCompass/commit/dfe7780ffa134f913f84281b53141cd4d3ca24a9
