### ISSUE TITLE
[Suggestion]: Provide any information on the located structure besides just the compass needle

### ISSUE THREAD

**Issue by Stray216** [Mrbysco/StructureCompass#5]
### General Info

- [X] I would like to propose new content
- [X] I would like to propose changes
- [ ] I would like to propose another thing

### Suggestion Description

As of right now, there is no way to tell if the located structure is 300'000 blocks or just 300 blocks away.
There is also no way to tell whether the compass points at world spawn or at a found structure, not unless you open your inventory and look the tooltip of the item itself.

It would be very nice to get more information and more conveniently.

One way to do this, like other compass mods also do, is through text on the HUD.
You could also write more information in the chat, like "Found [structure]! [distance] blocks away at [x and z]!" or similar.
Any of those things would also make it more apparent that clicking the compass will make it point to a different structure.
You could also make the compass loose its needle or spin randomly (like vanilla clock/compass in nether does) if no structure was found.

**Comment by Mrbysco** [comment]
A new build has been uploaded which will state the amount of blocks away the located structure is
