### ISSUE TITLE
[Bug]: Compass needle just waggles about in non-overworld locations

### ISSUE THREAD

**Issue by dpcollier128** [Mrbysco/StructureCompass#6]
### General Info

- [X] I am running a modpack
- [X] I can reproduce this issue consistently in single-player
- [ ] I can reproduce this issue consistently in multi-player
- [X] I have searched for this issue previously and it was either (1) not previously reported, or (2) previously fixed and I am having the same problem.
- [ ] I am crashing and can provide my crash report(s)
- [X] I am using the latest version of the mod

### Forge version

43.1.43

### Mod version

1.3.3

### Java version

Java 8 update 351

### Issue Description

The structure compass appears to exhibit default compass behavior whenever used within a non-overworld dimension (ie. waggle uselessly in many directions). This is both before and after selecting a destination. I have also noticed that the item sprite is identical to the default compass item, likely a bug or modpack configuration conflict.

I am using the All The Mods 8 modpack as shown here: https://www.curseforge.com/minecraft/modpacks/all-the-mods-8

**Comment by Mrbysco** [comment]
> The structure compass appears to exhibit default compass behavior whenever used within a non-overworld dimension

I'll look into it

> I have also noticed that the item sprite is identical to the default compass item, likely a bug or modpack configuration conflict.

That's intentional, I'm just re-using vanilla's compass model

**Comment by Mrbysco** [comment]
A new version has been uploaded to CurseForge which will be available shortly
