### ISSUE TITLE
[Bug]: Compass has no cooldown

### ISSUE THREAD

**Issue by Mihoshika** [Mrbysco/StructureCompass#7]
### General Info

- [ ] I am running a modpack
- [ ] I can reproduce this issue consistently in single-player
- [X] I can reproduce this issue consistently in multi-player
- [X] I have searched for this issue previously and it was either (1) not previously reported, or (2) previously fixed and I am having the same problem.
- [ ] I am crashing and can provide my crash report(s)
- [X] I am using the latest version of the mod

### Forge version

43.1.52

### Mod version

1.3.4

### Java version

1.19.2

### Issue Description

No cool down on using the tool. If you spam right click, it'll almost always lag a server.

**Comment by Mrbysco** [comment]
A cooldown has been added in https://github.com/Mrbysco/StructureCompass/commit/1f11ef0fb5eac119f18e17604c9ea607addd686f

**Comment by Mrbysco** [comment]
A new version is now available on Curseforge
