### ISSUE TITLE
[Suggestion]: 

### ISSUE THREAD

**Issue by Mihoshika** [Mrbysco/StructureCompass#8]
### General Info

- [X] I would like to propose new content
- [X] I would like to propose changes
- [ ] I would like to propose another thing

### Suggestion Description

From my understanding, this mod is supposed to function similarly to https://github.com/Samarium150/StructuresCompass. However, this one has a few issues that make it difficult to use effectively.  

Most notably, is the inability to choose whether or not to search existing chunks. On top of that, you are only given the distance in chat. No coordinates. This means that if you accidentally right click again, you lose the way towards the one you were initially traveling to.  

As in the previously mentioned mod which is similar in function, the ability to search previously generated chunks would allow you to find them easier.

In addition, a display showing how much further you have left to travel, when holding the compass, would be nice.

**Comment by Mrbysco** [comment]
I try to not give precise coordinates on purpose, Currently the `locateUnexplored` config option dictates whether it locates explored or unexplored structures.

I'll look what I can do about showing the distance left to travel
